name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: NB Classifier Test
      id: nb-classifier-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: NB Classifier Test
        setup-command: pip3 install pytest pandas argparse
        command: pytest
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        NB-CLASSIFIER-TEST_RESULTS: "${{steps.nb-classifier-test.outputs.result}}"
      with:
        runners: nb-classifier-test
